name: Send quiz
on: 
  schedule:
  - cron: '30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@main
      with:
        python-version: '>=3.6'
    - name: Install dependencies
      run: pip install -r requirements.txt
      
sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
sudo pip3 install pyopenssl
sudo pip3 install pyopenssl --upgrade

    - name: Send quiz
      run: python src/main.py
