name: Send quiz
on: 
  schedule:
  - cron: '30 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '>=3.6'
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Send quiz
      run: python src/main.py
